#!/bin/bash

function url(){
 echo "http"
}
url



function test(){
  for i in $@
  do
    echo -n "$i "
  done
}
test 1 2 4


#!/bin/bash

#定义函数
function show(){
    echo "Tutorial: $1"
    echo "URL: $2"
    echo "Author: "$3
    echo "Total $# parameters"
}

#调用函数
show C# http://c.biancheng.net/csharp/ Tom
