#!/bin/bash
read -p "请输入：" n
case $n in
1)
   echo "...1"
   ;;
2)
   echo "...2"
   ;;
3)
   echo "...3"
   ;;
[a-z])
   echo  "这是字母"
   ;;
[?!@#$])
   echo "这是特殊字符"
   ;;:wqZZ
*)
   echo "其他"
esac


还可以支持正则表达式
